import Link from "next/link";
import { ArrowRight, BookOpen, Check, Code2, Flame, Timer } from "lucide-react";

export default function HomePage() {
  return <main className="landing-page">
    <header className="landing-header"><Link className="brand" href="/"><span className="brand-mark"><span /></span><span className="brand-name">devflow</span></Link><span className="landing-header-note">A workspace for the work and the learning.</span><Link className="landing-login" href="/signin">Sign in <ArrowRight size={14} /></Link></header>
    <section className="landing-hero">
      <div className="landing-copy"><div className="landing-kicker"><span className="online-dot" /> YOUR PERSONAL GROWTH WORKSPACE</div><h1>Build.<br /><span>Learn.</span><br />Flow.</h1><p>One thoughtful place for the things you make, the words you’re learning, and the time you give them.</p><div className="landing-actions"><Link href="/today" className="button button-primary button-lg">Open your workspace <ArrowRight size={16} /></Link><span><Check size={14} /> Works offline. Your data stays yours.</span></div><div className="landing-footnote">No account needed to start. Your sample workspace is saved on this device.</div></div>
      <div className="preview-window" aria-label="Preview of the DevFlow workspace"><div className="preview-top"><span className="preview-dot" /><span className="preview-dot" /><span className="preview-dot" /><span className="preview-address">devflow / today</span><span className="preview-mini-mark">d</span></div><div className="preview-body"><div className="preview-rail"><span className="preview-logo">d</span><i className="selected" /><i /><i /><i /><i /><i /></div><div className="preview-content"><div className="preview-greeting"><small>WEDNESDAY, SEPTEMBER 30</small><b>Good morning, Atif.</b><span>A little progress, every day.</span></div><div className="preview-metrics"><div><small>FOCUS</small><b>42 <em>min</em></b></div><div><small>TO LEARN</small><b>5 <em>words</em></b></div><div><small>TO SHIP</small><b>3 <em>tasks</em></b></div></div><div className="preview-panels"><div className="preview-panel preview-task-panel"><div className="preview-panel-head"><span><Code2 size={13} /> IN MOTION</span><small>View all ↗</small></div><strong>Interactive Comments Section</strong><div className="preview-task"><span className="preview-check"><Check size={10} /></span>Build the reply state <i>Today</i></div><div className="preview-task"><span className="preview-check empty" /> Review mobile layout <i>Tomorrow</i></div><div className="preview-progress"><span /></div><small className="preview-caption">8 of 12 things done</small></div><div className="preview-panel preview-word-panel"><div className="preview-panel-head"><span><BookOpen size={13} /> GERMAN · A2</span><Flame size={13} className="preview-flame" /></div><div className="preview-word">behalten</div><div className="preview-pos">verb · to keep, to hold on to</div><p>„Ich möchte dieses Buch behalten.“</p><div className="preview-word-actions"><span>01 / 05</span><b>Know this word <ArrowRight size={11} /></b></div></div></div><div className="preview-focus"><span><Timer size={13} /> A little focus goes a long way.</span><strong>25:00 <i>Start a session</i></strong></div></div></div></div>
    </section>
    <footer className="landing-footer"><span>Build software. Learn languages. Track your progress.</span><span>Made for the long game <span className="footer-star">✳</span></span></footer>
  </main>;
}
